//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_data_H
#define METASPRITE_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define data_TILE_ORIGIN 0
#define data_TILE_W 8
#define data_TILE_H 8
#define data_WIDTH 128
#define data_HEIGHT 128
#define data_TILE_COUNT 256
#define data_PALETTE_COUNT 1
#define data_COLORS_PER_PALETTE 4
#define data_TOTAL_COLORS 4

BANKREF_EXTERN(data)

extern const palette_color_t data_palettes[4];
extern const uint8_t data_tiles[4096];

#endif
